### ISSUE TITLE
Can't run cura after build

### ISSUE THREAD

**Issue by rodrigopitanga** [Ultimaker/cura-build#103]
After running the build process successfully (except for `make package` as I'm on Parabola), can't run the generated binary:

```
[rodrigo@tequila4free cura-build]$ ./cura
python3.5: can't open file '/opt/cura/bin/cura': [Errno 2] No such file or directory
```

Running from `cura-build/inst` also leads to an error:
```
[rodrigo@tequila4free bin]$ pwd
/home/rodrigo/devel/cura-build/build/inst/bin
[rodrigo@tequila4free bin]$ ./cura 
Traceback (most recent call last):
  File "./cura", line 10, in <module>
    from UM.Platform import Platform
ImportError: No module named 'UM'
[rodrigo@tequila4free bin]$ 
```

Obviously some PYTHONPATH setting missing, would be nice to have it in the docs. Any clue?

**Comment by Ghostkeeper** [comment]
It would be fixed by putting Uranium's folder (containing the UM subfolder) in your PYTHONPATH environment variable.

Ideally this sort of thing would be arranged in the run script or in the installation. Isn't it?

**Comment by rodrigopitanga** [comment]
As stated in #7, I put python3/dist-packages on the PYTHONPATH environment variable. It still doesn't work. I wonder what people do or if you're just using `cura-build` for packaging purposes.

Here's my output:

```shell
[rodrigo@tequila4free bin]$ PYTHONPATH=.:../lib/python3/dist-packages:../lib ./cura
Traceback (most recent call last):
  File "./cura", line 10, in <module>
    from UM.Platform import Platform
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/UM/__init__.py", line 9, in <module>
    from .Application import Application
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/UM/Application.py", line 9, in <module>
    from UM.Controller import Controller
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/UM/Controller.py", line 4, in <module>
    from UM.Scene.Scene import Scene
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/UM/Scene/Scene.py", line 4, in <module>
    from UM.Scene.SceneNode import SceneNode
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/UM/Scene/SceneNode.py", line 4, in <module>
    from UM.Math.Matrix import Matrix
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/UM/Math/Matrix.py", line 7, in <module>
    import numpy
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/home/rodrigo/devel/cura-build/build/inst/lib/python3/dist-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

**Comment by rodrigopitanga** [comment]
Thanks, @awhiemstra 

One step further:

```shell
[rodrigo@tequila4free bin]$ LD_LIBRARY_PATH=../lib PYTHONPATH=.:../lib/python3/dist-packages:../lib ./cura
cura.CrashHandler.show [32]: An uncaught exception has occurred!
cura.CrashHandler.show [35]: Traceback (most recent call last):
cura.CrashHandler.show [35]:   File "./cura", line 47, in <module>
cura.CrashHandler.show [35]:     import Arcus #@UnusedImport
cura.CrashHandler.show [35]: ImportError: No module named 'Arcus'
```
There is no `Arcus` folder in lib/python3/dist-packages.
There is an `Arcus.so` file in lib/python3.5/site-packages

**Comment by awhiemstra** [comment]
Yeah something is messed up with the installation paths for Arcus. Simple solution is to move the .so file over to lib/python3/dist-packages . We have been working on an improved build system that should be better able to handle this but that one has been slightly stuck on Windows support.

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
