### ISSUE TITLE
Import Error: No module named 'Savitar' while running cx_Freeze

### ISSUE THREAD

**Issue by ewurman-dm** [Ultimaker/cura-build#123]
Hi,
I am trying to build Cura from the source code on a Windows 10 machine with Visual Studio 2017, Python3.6, Cmake 3.8.1 with Mingw Makefiles. I have followed the steps and gotten through the cmake step (but only after turning signing off and rewriting a line in CMakeList file to get rid of the CACHE FORCE in get_filename_component on line 23). Now I am at the mingw32-make step and it gets 98% complete but encounters an error while running cx_Freeze. The first error was that it was looking for a python3.5 folder instead of 3.6

[ 92%] Completed 'fdm_materials
[ 98%] Built target fdm_materials
[ 98%] Built target projects
Running cx_Freeze
running build_exe
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    executables = executables
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 218, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 149, in __init__
    self._VerifyConfiguration()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 468, in _VerifyConfiguration
    sourceFileName)
cx_Freeze.freezer.ConfigError: cannot find file/directory named C:\cura-build-master\build\inst\lib\python3.5\site-packages\UM\Qt\qml\UM
CMakeFiles\build_bundle.dir\build.make:56: recipe for target 'build_bundle' failed
mingw32-make[2]: *** [build_bundle] Error 1
CMakeFiles\Makefile2:369: recipe for target 'CMakeFiles/build_bundle.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/build_bundle.dir/all] Error 2
makefile:150: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

To try and fix this, I duplicated the python3.6 folder and renamed it 3.5. This led to another error about Import Error no module named Savitar. 

[ 92%] Completed 'fdm_materials'
[ 98%] Built target fdm_materials
[ 98%] Built target projects
Running cx_Freeze
running build_exe
Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    executables = executables
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 621, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 340, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 653, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\erikwurman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 350, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'Savitar'
CMakeFiles\build_bundle.dir\build.make:56: recipe for target 'build_bundle' failed
mingw32-make[2]: *** [build_bundle] Error 1
CMakeFiles\Makefile2:369: recipe for target 'CMakeFiles/build_bundle.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/build_bundle.dir/all] Error 2
makefile:150: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

I am having trouble finding any relevant information about this through google, part of which is because apparently a few days ago the tv series the Flash revealed its new villain, who just so happens to be named Savitar. Just my luck :). Anyways, any help would be appreciated, Thanks.

p.s. I have the cx_freeze 5.0.2 addition.

**Comment by Ghostkeeper** [comment]
Savitar happens to be named after the DC Comics villain :)

You're missing libSavitar in your Python installation.
1. Download here: https://github.com/Ultimaker/libSavitar
2. Compile using the same compiler as your CPython installation (most likely MSVC).
3. Install so that the Python bindings for Savitar are in your PYTHONPATH.

**Comment by ewurman-dm** [comment]
Great thanks! I was able to mingw32-make and mingw32-make package cura, but when I installed and tried to run the executable, I got an error saying no module named Arcus.

I also ran into this during the make. I assume the problems are related:

Missing modules:
? Arcus imported from UM.Backend.Backend, UM.Backend.SignalSocket, cura__main__
? Image imported from scipy.misc.pilutil
? ImageFilter imported from scipy.misc.pilutil
? PIL imported from scipy.misc.pilutil
? StringIO imported from numpy.lib.format, numpy.lib.utils, numpy.testing.utils, scipy._lib.six, six
? System imported from serial.serialcli
? System.IO.Ports imported from serial.serialcli
? __builtin__ imported from numpy, numpy.core.numeric, numpy.core.numerictypes, numpy.distutils.misc_util, numpy.lib._iotools, numpy.lib.function_base, numpy.ma.core, scipy._lib.six
? __main__ imported from bdb, pdb, pkg_resources, rlcompleter
? _curses imported from curses, curses.has_key
? _dummy_threading imported from dummy_threading
? _frozen_importlib imported from importlib, importlib.abc
? _frozen_importlib_external imported from importlib, importlib._bootstrap, importlib.abc
? _posixsubprocess imported from multiprocessing.util, subprocess
? _scproxy imported from urllib.request
? _sysconfigdata imported from sysconfig
? _winreg imported from numpy.distutils.cpuinfo, platform
? asyncio._overlapped imported from asyncio
? asyncio.selectors imported from asyncio
? backports.ssl_match_hostname imported from setuptools.ssl_support
? cPickle imported from numpy.core.numeric, numpy.lib.format, numpy.lib.npyio, numpy.ma.core
? ce imported from os
? certifi imported from setuptools.ssl_support
? cffi imported from scipy._lib._ccallback
? commands imported from numpy.distutils.cpuinfo
? copy_reg imported from numpy.core
? dummy_thread imported from numpy.core.arrayprint
? fcntl imported from UM.SaveFile, asyncio.unix_events, serial.serialposix, serial.tools.miniterm
? future_builtins imported from numpy.lib.npyio
? grp imported from distutils.archive_util, pathlib, shutil, tarfile
? java.lang imported from platform
? linalg_version imported from scipy.linalg.setup
? matplotlib.collections imported from scipy.spatial._plotutils
? matplotlib.pyplot imported from scipy.spatial._plotutils
? multiprocessing.AuthenticationError imported from multiprocessing.connection
? multiprocessing.BufferTooShort imported from multiprocessing.connection
? multiprocessing.SimpleQueue imported from concurrent.futures.process
? multiprocessing.TimeoutError imported from multiprocessing.pool
? multiprocessing.get_context imported from multiprocessing.managers, multiprocessing.pool, multiprocessing.sharedctypes
? multiprocessing.get_start_method imported from multiprocessing.spawn
? multiprocessing.set_start_method imported from multiprocessing.spawn
? netbios imported from uuid
? new imported from scipy.interpolate.rbf
? nose imported from numpy.testing.decorators, numpy.testing.noseclasses, numpy.testing.utils, scipy._lib._testutils
? nose.plugins imported from numpy.testing.noseclasses
? nose.plugins.base imported from numpy.testing.noseclasses
? nose.plugins.builtin imported from numpy.testing.nosetester
? nose.plugins.errorclass imported from numpy.testing.noseclasses
? nose.util imported from numpy.testing.noseclasses
? numarray imported from numpy.distutils.system_info
? numpy.core.float32 imported from numpy.testing.utils
? numpy.core.geterrobj imported from numpy.linalg.linalg
? numpy.core.intp imported from numpy.linalg.linalg
? numpy.core.isnat imported from numpy.testing.utils
? numpy.core.longdouble imported from numpy.linalg.linalg
? numpy.core.object_ imported from numpy.linalg.linalg
? numpy.core.signbit imported from numpy.testing.utils
? numpy_distutils imported from numpy.f2py.diagnose
? numpy_distutils.command.build_flib imported from numpy.f2py.diagnose
? numpy_distutils.command.cpuinfo imported from numpy.f2py.diagnose
? numpy_distutils.cpuinfo imported from numpy.f2py.diagnose
? numpy_distutils.fcompiler imported from numpy.f2py.diagnose
? org.python.core imported from copy, pickle
? org.python.modules.posix.PosixModule imported from setuptools.sandbox
? os.path imported from UM.Mesh.MeshFileHandler, UM.MimeTypeDatabase, UM.Qt.Bindings.ActiveToolProxy, UM.Qt.Bindings.ActiveViewProxy, UM.Qt.Bindings.DirectoryListModel, UM.Qt.Bindings.MeshFileHandlerProxy, UM.Qt.Bindings.Theme, UM.Resources, UM.SaveFile, UM.Settings.Models.SettingDefinitionsModel, cura.CuraApplication, cura.PrintInformation, cura.Settings.ContainerManager, cura.Settings.CuraContainerRegistry, cura.Settings.CuraContainerStack, distutils.file_util, numpy.core.memmap, os, pkg_resources, pkgutil, py_compile, scipy.linalg.setup, sysconfig, unittest, unittest.util
? pkg_resources.extern.appdirs imported from pkg_resources
? pkg_resources.extern.packaging imported from pkg_resources, setuptools.command.egg_info, setuptools.dist
? pkg_resources.extern.six imported from pkg_resources
? pkg_resources.extern.six.moves imported from pkg_resources
? pkg_resources.iter_entry_points imported from setuptools.command.egg_info
? pkg_resources.resource_string imported from setuptools.command.easy_install
? posix imported from os
? pwd imported from distutils.archive_util, distutils.util, getpass, http.server, netrc, pathlib, posixpath, shutil, tarfile, webbrowser
? scipy.special.xlogy imported from scipy.interpolate.rbf
? sets imported from numpy.distutils.command.build_ext, numpy.distutils.fcompiler, numpy.distutils.misc_util
? setuptools.extern.six imported from setuptools.command.bdist_egg, setuptools.command.develop, setuptools.command.easy_install, setuptools.command.egg_info, setuptools.command.sdist, setuptools.depends, setuptools.dist, setuptools.glob, setuptools.monkey, setuptools.package_index, setuptools.sandbox, setuptools.unicode_utils
? setuptools.extern.six.moves imported from setuptools, setuptools.command.easy_install, setuptools.command.egg_info, setuptools.command.py36compat, setuptools.command.setopt, setuptools.dist, setuptools.extension, setuptools.package_index, setuptools.sandbox, setuptools.ssl_support
? setuptools_svn imported from setuptools.command.egg_info
? six.moves imported from zeroconf
? stl._speedups imported from stl.stl
? termios imported from getpass, serial.serialposix, serial.tools.miniterm, tty
? thread imported from numpy.core.arrayprint
? urllib.splittag imported from setuptools.py26compat
? urllib2 imported from numpy.lib._datasource, setuptools.package_index
? urlparse imported from numpy.lib._datasource, serial.rfc2217, serial.urlhandler.protocol_alt, serial.urlhandler.protocol_loop, serial.urlhandler.protocol_socket, serial.urlhandler.protocol_spy
? vms_lib imported from platform
? win32api imported from distutils.msvccompiler
? win32com.client.gencache imported from setuptools.sandbox
? win32con imported from distutils.msvccompiler
? win32pdh imported from numpy.testing.utils
? win32wnet imported from uuid
? wincertstore imported from setuptools.ssl_support
This is not necessarily a problem - the modules may not be needed on this platform.

Thoughts?

**Comment by awhiemstra** [comment]
Arcus is a library provided by us that is used for communication between the frontend and the engine. You can get it from https://github.com/ultimaker/libArcus . The build procedure is about the same as Savitar, except that it needs Protobuf.

We actually do a bunch of dependency checks when running cmake for cura-build but I guess we forgot to add Arcus and Savitar.

**Comment by ewurman-dm** [comment]
Hi,
Thanks for the help. I did that and added arcus to my Path and PYTHONPATH. but I get the same ? output when I make and the same Error when I install and try and run. 

Error in sys.excepthook.
Exception 1
Original Exception 'No module named 'Arcus'

Would there be any reason why Cura cannot find these modules despite their existence in my PATH?

**Comment by Ghostkeeper** [comment]
There should be no need to add Arcus to your PATH, just to your PYTHONPATH.

If you open a Python terminal and type `import Arcus`, it should successfully import Arcus. If it doesn't, then your Arcus isn't on your PYTHONPATH or not correctly compiled with the same compiler as your CPython installation. It should be about the same as libSavitar...

Looks like you're also missing numpy and scipy. Those can just be installed using Pip though: `python3 -m pip install numpy` and `python3 -m pip install scipy`.

**Comment by ewurman-dm** [comment]
Ghostkeeper,

Thank you, I had forgotten to build Arcus. Unfortunately once I built it I encountered another error, this time about PyQt. The following is what I get trying to CMAKE cura now:
```
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PyQt: Found unsuitable version "", but required is at least
  "5.6" (found )
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:375 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPyQt.cmake:8 (find_package_handle_standard_args)
  projects/Uranium.cmake:7 (find_package)
  CMakeLists.txt:61 (include)

Configuring incomplete, errors occurred!
See also "C:/cura-build/build/CMakeFiles/CMakeOutput.log".
```

I got this with both the Cmake GUI and command prompt. I have PyQt5 installed in Python35\Lib\site-packages. I checked this as well with ```import PyQt5``` from the python shell, which has no errors. This issue seems similar or the same as  #122  that was closed by the creator without a solution.

**Comment by awhiemstra** [comment]
What do you get when running the following in Python?

```
import PyQt5.QtCore
PyQt5.QtCore.PYQT_VERSION_STR
```

**Comment by ewurman-dm** [comment]
Awhiemstra,

Good catch. The python shell quits if I run ```import PyQt5.QtCore```.
 Additionally, if I run the following,
```
import PyQt5
PyQt5.QtCore.PYQT_VERSION_STR
```
I get the following error:
``` AttributeError: module 'PyQt5' has no attribute 'QtCore' ```

Have you encountered (and hopefully fixed) this issue before?

**Comment by Ghostkeeper** [comment]
From [this mailing list](https://riverbankcomputing.com/pipermail/pyqt/2016-July/037816.html) I gather that you could get that error when it can't properly find the Qt DLLs.

**Comment by victorevector** [comment]
@ewurman-dm any news on your end? I was running into the same issue except the following commands do not produce errors:

~~~
import PyQt5
PyQt5.QtCore.PYQT_VERSION_STR
~~~

**Comment by Ghostkeeper** [comment]
What does the output of that command say, @victorevector?

**Comment by victorevector** [comment]
@Ghostkeeper it outputs `5.8.2` but I also found some interesting behavior...

The following will lead to `AttributeError: module 'PyQt5' has no attribute 'QtCore'`:
~~~
>>> import PyQt5
>>> PyQt5.QtCore.PYQT_VERSION_STR
AttributeError: module 'PyQt5' has no attribute 'QtCore'
~~~

The following will NOT lead to the error above:
~~~
>>> import PyQt5.QtCore
>>> PyQt5.QtCorePYQT_VERSION_STR
'5.8.2'
~~~

**Comment by Ghostkeeper** [comment]
Maybe this has an answer for you? https://riverbankcomputing.com/pipermail/pyqt/2016-July/037816.html

The guy uninstalled previous versions of PyQt5 to get it working.

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
