### ISSUE TITLE
Cura crashed after load and when import Arcus,Arcus use 80% of my memory

### ISSUE THREAD

**Issue by IwalkerI** [Ultimaker/cura-build#128]
This is my cura.log I think there has too many wrong...:

    2017-07-13 12:25:04,047 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin FileLogger
    2017-07-13 12:25:04,187 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin GCodeProfileReader
    2017-07-13 12:25:04,281 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin GCodeReader
    2017-07-13 12:25:04,375 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin GCodeWriter
    2017-07-13 12:25:04,546 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin ImageReader
    2017-07-13 12:25:05,576 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin LayerView
    2017-07-13 12:25:05,903 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin LegacyProfileReader
    2017-07-13 12:25:07,885 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin LocalFileOutputDevice
    2017-07-13 12:25:08,009 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin MachineSettingsAction
    2017-07-13 12:25:13,672 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin OctoPrintPlugin
    2017-07-13 12:25:13,844 - WARNING - UM.Preferences.getValue [81]: Tried to get the value of non-existing setting cura/active_mode.
    2017-07-13 12:25:13,844 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin PerObjectSettingsTool
    2017-07-13 12:25:13,891 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin PluginBrowser
    2017-07-13 12:25:14,000 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin PostProcessingPlugin
    2017-07-13 12:25:14,281 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin RemovableDriveOutputDevice
    2017-07-13 12:25:15,123 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin SliceInfoPlugin
    2017-07-13 12:25:15,279 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin SolidView
    2017-07-13 12:25:15,404 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin CameraTool
    2017-07-13 12:25:15,435 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin MirrorTool
    2017-07-13 12:25:15,685 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin RotateTool
    2017-07-13 12:25:15,794 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin ScaleTool
    2017-07-13 12:25:15,841 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin SelectionTool
    2017-07-13 12:25:15,872 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin TranslateTool
    2017-07-13 12:25:15,934 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin UltimakerMachineActions
    2017-07-13 12:25:16,168 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin UM3NetworkPrinting
    2017-07-13 12:25:17,962 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin UpdateChecker
    2017-07-13 12:25:17,993 - INFO - UpdateChecker.UpdateCheckerJob.run [43]: Checking for new version of cura
    2017-07-13 12:25:18,477 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin USBPrinting
    2017-07-13 12:25:18,898 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin VersionUpgrade21to22
    2017-07-13 12:25:19,039 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin VersionUpgrade22to24
    2017-07-13 12:25:19,163 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin VersionUpgrade25to26
    2017-07-13 12:25:19,257 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin VersionUpgrade26to27
    2017-07-13 12:25:19,288 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin SimpleView
    2017-07-13 12:25:19,351 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin X3DReader
    2017-07-13 12:25:19,631 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin XmlMaterialProfile
    2017-07-13 12:25:19,741 - INFO - UM.PluginRegistry.loadPlugin [231]: Loaded plugin XRayView
    2017-07-13 12:25:19,787 - INFO - UM.Qt.QtApplication.__init__ [112]: Command line arguments: {'qmljsdebugger': None, 'file': [], 'external-backend': False, 'disable-textures': False, 'single_instance': False}
    2017-07-13 12:25:20,833 - INFO - UpdateChecker.UpdateCheckerJob.run [77]: Found a new version of the software. Spawning message
    2017-07-13 12:25:21,035 - CRITICAL - cura.CrashHandler.show [39]: An uncaught exception has occurred!
    2017-07-13 12:25:21,145 - CRITICAL - cura.CrashHandler.show [42]: Traceback (most recent call last):
    2017-07-13 12:25:21,145 - CRITICAL - cura.CrashHandler.show [42]:   File "E:/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev0/msys/local/cura-build-master/build2/inst/lib/python3.5/site-packages/cura\CuraApplication.py", line 701, in event
    2017-07-13 12:25:21,145 - CRITICAL - cura.CrashHandler.show [42]:     return super().event(event)
    2017-07-13 12:25:21,160 - CRITICAL - cura.CrashHandler.show [42]:   File "E:/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev0/msys/local/cura-build-master/build2/inst/lib/python3.5/site-packages/UM\Qt\QtApplication.py", line 261, in event
    2017-07-13 12:25:21,160 - CRITICAL - cura.CrashHandler.show [42]:     event._function_event.call()
    2017-07-13 12:25:21,160 - CRITICAL - cura.CrashHandler.show [42]:   File "E:/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev0/msys/local/cura-build-master/build2/inst/lib/python3.5/site-packages/UM\Event.py", line 189, in call
    2017-07-13 12:25:21,176 - CRITICAL - cura.CrashHandler.show [42]:     self._function(*self._args, **self._kwargs)
    2017-07-13 12:25:21,176 - CRITICAL - cura.CrashHandler.show [42]:   File "E:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\msys\local\cura-build-master\build2\package\plugins\CuraEngineBackend\CuraEngineBackend.py", line 519, in _createSocket
    2017-07-13 12:25:21,176 - CRITICAL - cura.CrashHandler.show [42]:     super()._createSocket(os.path.abspath(os.path.join(PluginRegistry.getInstance().getPluginPath(self.getPluginId()), "Cura.proto")))
    2017-07-13 12:25:21,191 - CRITICAL - cura.CrashHandler.show [42]:   File "E:/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev0/msys/local/cura-build-master/build2/inst/lib/python3.5/site-packages/UM\Backend\Backend.py", line 234, in _createSocket
    2017-07-13 12:25:21,191 - CRITICAL - cura.CrashHandler.show [42]:     if not self._socket.registerAllMessageTypes(protocol_file):
    2017-07-13 12:25:21,191 - CRITICAL - cura.CrashHandler.show [42]: TypeError: Socket.registerAllMessageTypes(): argument 1 has unexpected type 'str'
    2017-07-13 12:25:21,285 - INFO - UM.VersionUpgradeManager.upgrade [112]: Looking for old configuration files to upgrade.
    2017-07-13 12:26:16,525 - WARNING - UM.Settings.ContainerStack.addMetaDataEntry [161]: Meta data with key machine was already added.
    2017-07-13 12:26:16,525 - WARNING - UM.Settings.ContainerStack.addMetaDataEntry [161]: Meta data with key machine was already added.
    2017-07-13 12:26:16,665 - DEBUG - UM.Settings.ContainerRegistry.load [214]: Loading data into container registry took 36.316863775253296 seconds
    2017-07-13 12:26:16,805 - DEBUG - UM.Controller.setActiveView [84]: Setting active view to SolidView
    2017-07-13 12:26:23,373 - DEBUG - OctoPrintPlugin.DiscoverOctoPrintAction._createAdditionalComponentsView [171]: Creating additional ui components for OctoPrint-connected printers.
    2017-07-13 12:26:24,527 - DEBUG - UM.Qt.Bindings.Theme.load [165]: Loading theme file: E:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\msys\local\cura-build-master\build2\package\resources\themes\cura\theme.json
    2017-07-13 12:26:26,009 - DEBUG - UM.Qt.Bindings.Theme.load [232]: Loaded theme E:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\msys\local\cura-build-master\build2\package\resources\themes\cura
    2017-07-13 12:26:27,991 - DEBUG - UM3NetworkPrinting.DiscoverUM3Action._createAdditionalComponentsView [138]: Creating additional ui components for UM3.
    2017-07-13 12:26:28,771 - DEBUG - UM3NetworkPrinting.DiscoverUM3Action.startDiscovery [38]: Starting printer discovery.
    2017-07-13 12:26:29,223 - DEBUG - UM.Mesh.MeshData.approximateConvexHull [392]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.12480020523071289 seconds. 121 input vertices. 121 output vertices.
    2017-07-13 12:26:33,139 - DEBUG - UM.Backend.Backend._createSocket [213]: Previous socket existed. Closing that first.
    2017-07-13 12:26:33,357 - CRITICAL - cura.CrashHandler.show [39]: An uncaught exception has occurred!
    2017-07-13 12:26:33,357 - CRITICAL - cura.CrashHandler.show [42]: Traceback (most recent call last):
    2017-07-13 12:26:33,388 - CRITICAL - cura.CrashHandler.show [42]:   File "E:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\msys\local\cura-build-master\build2\package\plugins\CuraEngineBackend\CuraEngineBackend.py", line 208, in slice
    2017-07-13 12:26:33,388 - CRITICAL - cura.CrashHandler.show [42]:     self._createSocket()
    2017-07-13 12:26:33,388 - CRITICAL - cura.CrashHandler.show [42]:   File "E:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\msys\local\cura-build-master\build2\package\plugins\CuraEngineBackend\CuraEngineBackend.py", line 519, in _createSocket
    2017-07-13 12:26:33,404 - CRITICAL - cura.CrashHandler.show [42]:     super()._createSocket(os.path.abspath(os.path.join(PluginRegistry.getInstance().getPluginPath(self.getPluginId()), "Cura.proto")))
    2017-07-13 12:26:33,404 - CRITICAL - cura.CrashHandler.show [42]:   File "E:/mingw-w64/x86_64-7.1.0-posix-seh-rt_v5-rev0/msys/local/cura-build-master/build2/inst/lib/python3.5/site-packages/UM\Backend\Backend.py", line 234, in _createSocket
    2017-07-13 12:26:33,404 - CRITICAL - cura.CrashHandler.show [42]:     if not self._socket.registerAllMessageTypes(protocol_file):
    2017-07-13 12:26:33,419 - CRITICAL - cura.CrashHandler.show [42]: TypeError: Socket.registerAllMessageTypes(): argument 1 has unexpected type 'str'
    2017-07-13 12:26:41,297 - DEBUG - AutoSave.AutoSave._onTimeout [48]: Autosaving preferences, instances and profiles

**Comment by Ghostkeeper** [comment]
Edited your report a bit for readability...

> TypeError: Socket.registerAllMessageTypes(): argument 1 has unexpected type 'str'

This is weird because [registerAllMessageTypes](https://github.com/Ultimaker/libArcus/blob/master/src/Socket.cpp#L73) does expect a string...

How did you build the Python bindings for libArcus? Using MSVC or MinGW?

**Comment by IwalkerI** [comment]
@Ghostkeeper 
Using MinGW 64  to build https://github.com/Ultimaker/libArcus .When I get the Arcus.pyd,It's install on C:\Program Files (x86)\arcus\lib\python3.5\site-packages(cause my cmake option),but it's 15.7MB large!It's there any problem?And when use python ide to import it,not only you have Arcus.pyd in my site-package but also libArcus.dll ! I think there has some wrongs with Arcus cause large memory....(Oh,Cura crash problem is solved when I update my PYQT from 5.6 to 5.7....But large memory use still exist)

**Comment by Ghostkeeper** [comment]
If you're going to use the master branch, you'd better already upgrade to 5.8. Otherwise it crashes once you make one of the new Extruder-per-Feature settings visible.

For Windows you basically need to compile libArcus twice, sadly.

libArcus is required by CuraEngine if it needs to communicate with Cura's front-end. Since CuraEngine is compiled with MinGW, libArcus is also compiled with MinGW.

libArcus is also required by Cura's front-end to communicate with CuraEngine. Since Cura's front-end is based on Python and Python is compiled with MSVC, you need to compile the Python bindings with MSVC.

This goes for all Python bindings for CPython (so basically all Python bindings on Windows ever since CPython is the only Python implementation with proper native support). In Cura's case, also libSavitar needs to be compiled with MSVC.

**Comment by IwalkerI** [comment]
Thank you @Ghostkeeper ....But there's someting wrong with my  MSVC ... It's crashed every time.It's there any Arcus.pyd and Savitar.pyd(already compiled) to support my Win7 x64 to solve this problem?

**Comment by awhiemstra** [comment]
Assuming you are using Python 3.5, you can take the Arcus.pyd and Savitar.pyd from one of the releases of Cura.

**Comment by IwalkerI** [comment]
@awhiemstra thanks,Yeah,I'm using Python 3.5!I'll try it again with your suggestion , If there any new questions, I'll be back...

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
