### ISSUE TITLE
At 98% packaging step cx_Freezer looking in the wrong place

### ISSUE THREAD

**Issue by kirilledelman** [Ultimaker/cura-build#176]
Hi I keep trying to compile Cura, maybe I'll be able to one day!

So close:
```
[ 90%] Completed 'cura-binary-data'
[ 96%] Built target cura-binary-data
[ 96%] Built target projects
[ 98%] Packaging Projects...
running bdist_mac
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    executables = executables
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cx_Freeze/dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cx_Freeze/macdist.py", line 232, in run
    self.run_command('build')
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cx_Freeze/dist.py", line 218, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cx_Freeze/freezer.py", line 150, in __init__
    self._VerifyConfiguration()
  File "/Users/kirilledelman/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cx_Freeze/freezer.py", line 470, in _VerifyConfiguration
    sourceFileName)
cx_Freeze.freezer.ConfigError: cannot find file/directory named /Users/kirilledelman/cura-build/build/inst/lib/python3.5/site-packages/UM/Qt/qml/UM
make[2]: *** [packaging] Error 1
make[1]: *** [CMakeFiles/packaging.dir/all] Error 2
make: *** [all] Error 2
```
I noticed that `inst/lib/` actually contains `python3.6`, and this path is valid: `/Users/kirilledelman/cura-build/build/inst/lib/python3.6/site-packages/UM/Qt/qml/UM`, but for some reason looks like cx_Freeze is looking for python3.5

Any clues?

**Comment by Ghostkeeper** [comment]
Maybe you could try changing these lines to search for Python 3.6:

* https://github.com/Ultimaker/cura-build/blob/3a0d7d4382c4b2e5e1c8b978c2fd8dbde9ffe6b2/projects/Uranium.cmake#L1
* https://github.com/Ultimaker/cura-build/blob/6f1d1856a1275b2adad62a9b94dcf937a5551909/projects/libCharon.cmake#L1

PythonInterp's CMake find package should find the newest version it can find though...

**Comment by LipuFei** [comment]
No response for a long time. Closing this one.

**Comment by roseg0ld** [comment]
I am having this same exact issue, I changed both of those as well as in setup.py and it didn't help much. Changing setup.py did change the directory that couldn't be found however:

`
[ 98%] Packaging Projects...
running bdist_mac
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    executables = executables
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/macdist.py", line 232, in run
    self.run_command('build')
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/dist.py", line 218, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 150, in __init__
    self._VerifyConfiguration()
  File "/usr/local/lib/python3.7/site-packages/cx_Freeze/freezer.py", line 470, in _VerifyConfiguration
    sourceFileName)
cx_Freeze.freezer.ConfigError: cannot find file/directory named /Users/Zach/Desktop/Hydra/cura-build/cmake/lib/qml/Qt
make[2]: *** [packaging] Error 1
make[1]: *** [CMakeFiles/packaging.dir/all] Error 2
make: *** [all] Error 2`

**Comment by LipuFei** [comment]
@kirilledelman @roseg0ld 
The current `master` branch only works with Python 3.5. For Python 3.6+, many things need to be changed, including using a newer `cxFreeze` and changing some paths in the build scripts, because `python3.6` and `python3.7` together with `cxFreeze` does many things differently, such as where a file will be put by default.

There is a branch called `py3.6` in this repository and https://github.com/Ultimaker/cura-build-environment that uses Python 3.6. It's WIP but as far as I have tested, the builds for Linux and Windows seem to work.
