### ISSUE TITLE
Error on building Cura on Ubuntu 15.04

### ISSUE THREAD

**Issue by dmandala** [Ultimaker/cura-build#20]
script runs to almost completion with no apparent errors(I've done it a bunch of times adding debug info to the build script) then when it attempts to run Cura.  I have no idea what to try to fix this.

Link:/home/linaro/dev/CuraEngine/build/CuraEngine
Starting Cura......
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/linaro/dev/Cura/cura/CrashHandler.py", line 8, in <module>
    from UM.i18n import i18nCatalog
ImportError: No module named 'UM'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 14, in <module>
    import cura.CuraApplication
  File "/home/linaro/dev/Cura/cura/CuraApplication.py", line 9, in <module>
    from OpenGL import GL
ImportError: No module named 'OpenGL'

**Comment by dmandala** [comment]
A friend suggested to do the following and it works on x86:
$ export PYTHONPATH=/usr/local/lib/python3/dist-packages 
$ python3 cura_app.py

Not sure what the correct fix really is

**Comment by dmandala** [comment]
On ARMv8 (64-bit ARM CPU) in order to solve the no module named OpenGL needed to install: apt-get install python-opengl python3-opengl

**Comment by TMHogenhout** [comment]
Thanks! We're starting with a Q&A page. I put this solution in it as well.
