### ISSUE TITLE
Escaping in paths when running after build

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/cura-build#26]
Target platform: Win32
Host platform: Windows 8 x64

I've built an installer for a Windows 32 build. For some reason it still thinks it's a 64-bit build and installs in the 64-bit folder but that's probably irrelevant.

When I run the newly installed Cura, I get the following error:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Persoonlijk\Projecten\cura-build\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py", line 6, in <module>
    from PyQt5.QtCore import QT_VERSION_STR, PYQT_VERSION_STR, QCoreApplication
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Kan opgegeven module niet vinden.) 'C:\\Program Files\\Cura 2.0\\PyQt5.QtCore.pyd'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 23, in <module>
  File "C:\Persoonlijk\Projecten\cura-build\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 6, in <module>
    from UM.Qt.QtApplication import QtApplication
  File "C:\Persoonlijk\Projecten\cura-build\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 9, in <module>
    from PyQt5.QtCore import Qt, QObject, QCoreApplication, QEvent, pyqtSlot, QLocale, QTranslator, QLibraryInfo, PYQT_VERSION_STR
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Kan opgegeven module niet vinden.) 'C:\\Program Files\\Cura 2.0\\PyQt5.QtCore.pyd'
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Persoonlijk\Projecten\cura-build\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py", line 6, in <module>
    from PyQt5.QtCore import QT_VERSION_STR, PYQT_VERSION_STR, QCoreApplication
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Kan opgegeven module niet vinden.) 'C:\\Program Files\\Cura 2.0\\PyQt5.QtCore.pyd'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 23, in <module>
  File "C:\Persoonlijk\Projecten\cura-build\build\inst\lib\python3.4\site-packages\cura\CuraApplication.py", line 6, in <module>
    from UM.Qt.QtApplication import QtApplication
  File "C:\Persoonlijk\Projecten\cura-build\build\inst\lib\python3.4\site-packages\UM\Qt\QtApplication.py", line 9, in <module>
    from PyQt5.QtCore import Qt, QObject, QCoreApplication, QEvent, pyqtSlot, QLocale, QTranslator, QLibraryInfo, PYQT_VERSION_STR
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Kan opgegeven module niet vinden.) 'C:\\Program Files\\Cura 2.0\\PyQt5.QtCore.pyd'
```

This might be from multiple runs. I'm not quite sure, since the first run was not as administrator, the second run didn't seem to do anything and the third run was properly as administrator and returned an error (Cura's standard pop-up telling me to read the log).

The file `C:\Program Files\Cura 2.0\PyQt5.QtCore.pyd` does exist. However, it seems it is trying to read directories with double backslashes.

The problem does not occur when using separate repositories, so it is an issue regarding cura-build.

**Comment by LipuFei** [comment]
We don't target Windows 32-bit any more, so I'll close this issue.
