### ISSUE TITLE
Make fails on OSX

### ISSUE THREAD

**Issue by marcosfg** [Ultimaker/cura-build#30]
I am having trouble running the make command. I receive an error informing that no module named 'setuptools' is installed. I'm running OSX El Capital 10.11.2 and have installed both python 2.7.11 and python 3.4.3

I have already installed and upgraded setuptools using pip3 and pip2. However I'm still receiving the same error.

Any help? here's the terminal output.

[ 14%] Completed 'Protobuf'
[ 14%] Built target Protobuf
[ 14%] Built target Python
[ 14%] Performing update step for 'Protobuf-python'
Current branch master is up to date.
[ 14%] No configure step for 'Protobuf-python'
[ 14%] Performing build step for 'Protobuf-python'
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from setuptools import setup, Extension, find_packages
ImportError: No module named 'setuptools'
make[2]: **\* [Protobuf-python-prefix/src/Protobuf-python-stamp/Protobuf-python-build] Error 1
make[1]: **\* [CMakeFiles/Protobuf-python.dir/all] Error 2
make: **\* [all] Error 2

Thank you for your help.

**Comment by awhiemstra** [comment]
Python is being built by the cura-build. However, since OSX 10.11 Apple removed the OpenSSL headers, causing the build of Python to not build the _ssl module. This in turn causes setuptools not to build. To fix this,  we had to manually install OpenSSL since Python's _ssl module only works with OpenSSL.

**Comment by mikenew12** [comment]
FYI you can install openssl with homebrew:

    brew install openssl
    brew link openssl --force

Then in `cura-build/build`

    make clean
    make

**Comment by marcosfg** [comment]
Thank you very much for your help. However I still run make successfully. After about an hour of compiling and downloading requirements, I have received the following error:

building 'dfftpack' library
error: library dfftpack has Fortran sources but no Fortran compiler found
make[2]: *** [Scipy-prefix/src/Scipy-stamp/Scipy-build] Error 1
make[1]: *** [CMakeFiles/Scipy.dir/all] Error 2
make: *** [all] Error 2

I tried to install scipy using pip3, however the output says that the requirement is already satisfied...

dem-nb0032:build marcosgomes$ pip3 install scipy
Requirement already satisfied (use --upgrade to upgrade): scipy in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages

any help?

Thank you

**Comment by marcosfg** [comment]
I have found a way to proceed a bit further. Apparently it was some error related with the fortran compiler which is bundled with gcc. The gcc that I had installed did not have it:

brew install gcc

I'm having another issue in:

customize Gnu95FCompiler
customize Gnu95FCompiler using build_clib
building 'mach' library
using additional config_fc from setup script for fortran compiler: {'noopt': ('scipy/integrate/setup.py', 1)}
customize Gnu95FCompiler
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -g -fno-second-underscore -fPIC
Fortran fix compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC
compile options: '-I/Users/marcosgomes/git/cura-build/build/inst/lib/python3.4/site-packages/numpy/core/include -c'
gfortran:f77: scipy/integrate/mach/d1mach.f
/var/folders/xz/70ctspmd60j5bpzyxffbcwb00000gn/T//ccdj4NNz.s:592:suffix or operands invalid for `movq'
/var/folders/xz/70ctspmd60j5bpzyxffbcwb00000gn/T//ccdj4NNz.s:594:suffix or operands invalid for `movq'
/var/folders/xz/70ctspmd60j5bpzyxffbcwb00000gn/T//ccdj4NNz.s:592:suffix or operands invalid for `movq'
/var/folders/xz/70ctspmd60j5bpzyxffbcwb00000gn/T//ccdj4NNz.s:594:suffix or operands invalid for `movq'
error: Command "/usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -I/Users/marcosgomes/git/cura-build/build/inst/lib/python3.4/site-packages/numpy/core/include -c -c scipy/integrate/mach/d1mach.f -o build/temp.macosx-10.11-x86_64-3.4/scipy/integrate/mach/d1mach.o" failed with exit status 1
make[2]: *** [Scipy-prefix/src/Scipy-stamp/Scipy-build] Error 1
make[1]: *** [CMakeFiles/Scipy.dir/all] Error 2
make: *** [all] Error 2

**Comment by awhiemstra** [comment]
Unfortunately you seem to run into a fortran build issue from Scipy. I would not know a solution for it, since it is a third-party dependency that is included.

If you do not mind installing a bunch of stuff through pip or brew, you can disable building python and python related packages from CMake. Then you would not need to compile them manually.

**Comment by soyersoyer** [comment]
Is Scipy necessary? I have built and run cura on osx without scipy. What is it used for?

**Comment by nallath** [comment]
If I recall correctly we use some operations in scipi.

**Comment by Ghostkeeper** [comment]
It's optional, so it should still work without Scipy. It's used only for computing the convex hull faster (the shadow that appears below the model that indicates the collision area of an object).

**Comment by adjavaherian** [comment]
I'm getting a different make error: 

[ 23%] Performing build step for 'Py2App'
Traceback (most recent call last):
  File "setup.py", line 277, in <module>
    import setuptools
ImportError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "setup.py", line 279, in <module>
    use_setuptools()
  File "setup.py", line 188, in use_setuptools
    return _do_download(os.path.abspath(os.curdir))
  File "setup.py", line 175, in _do_download
    tarball = download_setuptools(packagename, to_dir)
  File "setup.py", line 198, in download_setuptools
    chksum, url = get_pypi_src_download(packagename)
  File "setup.py", line 54, in get_pypi_src_download
    fp = urllib.urlopen(url)
  File "/Users/Amir/Desktop/Ultimaker/cura-build/build/inst/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Amir/Desktop/Ultimaker/cura-build/build/inst/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/Users/Amir/Desktop/Ultimaker/cura-build/build/inst/lib/python3.4/urllib/request.py", line 486, in _open
    'unknown_open', req)
  File "/Users/Amir/Desktop/Ultimaker/cura-build/build/inst/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/Users/Amir/Desktop/Ultimaker/cura-build/build/inst/lib/python3.4/urllib/request.py", line 1252, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
make[2]: *** [Py2App-prefix/src/Py2App-stamp/Py2App-build] Error 1
make[1]: *** [CMakeFiles/Py2App.dir/all] Error 2
```

and setuptools is clearly installed.  Are you building yet another Python as part of cura-build?

**Comment by Ghostkeeper** [comment]
Yes, Python is optionally built from source on OSX: https://github.com/Ultimaker/cura-build/blob/master/CMakeLists.txt#L121

It seems that whatever Python installation that generated doesn't have HTTPS support. That would be a new issue.

As a workaround I suggest turning the "BUILD_PYTHON" CMake option off and just use your own Python.

**Comment by awhiemstra** [comment]
You need OpenSSL for the SSL python module. The SSL module is required for setuptools. Apple in their 'wisdom' decided to remove OpenSSL from OSX 10.11. So you will need to install OpenSSL through brew or something similar to get SSL support.

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
