### ISSUE TITLE
 Error: Unable to create the C++ code.  

### ISSUE THREAD

**Issue by macaddr** [Ultimaker/cura-build#45]
deepin Linux 15.11 64bit
do as README
meet error

> gkh@gkh-office:/home/d/curaProJt/cura-build/build$ make package[  0%] Built target Python
> [  7%] Built target Sip
> [ 15%] Built target Protobuf
> [ 16%] Performing update step for 'Arcus'
> 当前分支 HEAD 是最新的。
> [ 17%] Performing configure step for 'Arcus'
> -- Found SIP version: 4.17
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/d/curaProJt/cura-build/build/Arcus-prefix/src/Arcus-build
> [ 18%] Performing build step for 'Arcus'
> [ 35%] Built target Arcus
> [100%] Built target python_module_Arcus
> [ 19%] Performing install step for 'Arcus'
> [ 35%] Built target Arcus
> [100%] Built target python_module_Arcus
> Install the project...
> -- Install configuration: ""
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/lib/python3/dist-packages/Arcus.so
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/lib/libArcus.a
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/include/Arcus/Socket.h
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/include/Arcus/SocketListener.h
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/include/Arcus/Types.h
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/include/Arcus/ArcusExport.h
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/include/Arcus/MessageTypeStore.h
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/include/Arcus/Error.h
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/lib/cmake/Arcus/Arcus-targets.cmake
> -- Installing: /home/d/curaProJt/cura-build/build/inst/lib/cmake/Arcus/Arcus-targets-noconfig.cmake
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/lib/cmake/Arcus/ArcusConfig.cmake
> -- Up-to-date: /home/d/curaProJt/cura-build/build/inst/lib/cmake/Arcus/ArcusConfigVersion.cmake
> [ 19%] Completed 'Arcus'
> [ 22%] Built target Arcus
> [ 29%] Built target Qt
> [ 30%] Performing configure step for 'PyQt'
> Querying qmake about your Qt installation...
> Determining the details of your Qt installation...
> This is the GPL version of PyQt 5.4.2 (licensed under the GNU General Public
> License) for Python 3.4.4 on linux.
> Found the license file pyqt-gpl.sip.
> Checking to see if the QtGui module should be built...
> Checking to see if the QtHelp module should be built...
> Checking to see if the QtMultimedia module should be built...
> Checking to see if the QtMultimediaWidgets module should be built...
> Checking to see if the QtNetwork module should be built...
> Checking to see if the QtOpenGL module should be built...
> Checking to see if the QtPrintSupport module should be built...
> Checking to see if the QtQml module should be built...
> Checking to see if the QtQuick module should be built...
> Checking to see if the QtSql module should be built...
> Checking to see if the QtSvg module should be built...
> Checking to see if the QtTest module should be built...
> Checking to see if the QtWebKit module should be built...
> Checking to see if the QtWebKitWidgets module should be built...
> Checking to see if the QtWidgets module should be built...
> Checking to see if the QtXml module should be built...
> Checking to see if the QtXmlPatterns module should be built...
> Checking to see if the QtDesigner module should be built...
> Checking to see if the QAxContainer module should be built...
> Checking to see if the QtDBus module should be built...
> Checking to see if the QtSensors module should be built...
> Checking to see if the QtSerialPort module should be built...
> Checking to see if the QtX11Extras module should be built...
> Checking to see if the QtBluetooth module should be built...
> Checking to see if the QtMacExtras module should be built...
> Checking to see if the QtPositioning module should be built...
> Checking to see if the QtWinExtras module should be built...
> Checking to see if the QtQuickWidgets module should be built...
> Checking to see if the QtWebSockets module should be built...
> Checking to see if the Enginio module should be built...
> Checking to see if the QtWebChannel module should be built...
> Checking to see if the QtWebEngineWidgets module should be built...
> Checking to see if the dbus support module should be built...
> DBus v1 does not seem to be installed.
> Qt v5.5.1 (Open Source) is being used.
> The qmake executable is /home/d/curaProJt/cura-build/build/inst/bin/qmake.
> Qt is built as a shared library.
> SIP 4.17 is being used.
> The sip executable is /home/d/curaProJt/cura-build/build/inst/bin/sip.
> These PyQt5 modules will be built: QtCore, QtGui, QtNetwork, QtPrintSupport,
> QtQml, QtSql, QtSvg, QtTest, QtWidgets, QtXml, QtDBus.
> The PyQt5 Python package will be installed in
> /home/d/curaProJt/cura-build/build/inst/lib/python3/dist-packages.
> PyQt5 is being built with generated docstrings.
> PyQt5 is being built with 'protected' redefined as 'public'.
> The Designer plugin will be installed in
> /home/d/curaProJt/cura-build/build/inst/lib/plugins/designer.
> The qmlscene plugin will be installed in
> /home/d/curaProJt/cura-build/build/inst/lib/plugins/PyQt5.
> The PyQt5 .sip files will be installed in
> /home/d/curaProJt/cura-build/build/inst/share/sip.
> pyuic5, pyrcc5 and pylupdate5 will be installed in
> /home/d/curaProJt/cura-build/build/inst/bin.
> The interpreter used by pyuic5 is /usr/bin/python3.4.
> Generating the C++ source for the QtCore module...
> Embedding sip flags...
> Generating the .pro file for the QtCore module...
> Generating the C++ source for the QtGui module...
> Error: Unable to create the C++ code.
> CMakeFiles/PyQt.dir/build.make:110: recipe for target 'PyQt-prefix/src/PyQt-stamp/PyQt-configure' failed
> make[2]: **\* [PyQt-prefix/src/PyQt-stamp/PyQt-configure] Error 1
> CMakeFiles/Makefile2:332: recipe for target 'CMakeFiles/PyQt.dir/all' failed
> make[1]: **\* [CMakeFiles/PyQt.dir/all] Error 2
> Makefile:105: recipe for target 'all' failed
> make: **\* [all] Error 2
> gkh@gkh-office:/home/d/curaProJt/cura-build/build$ 
> 
> i need help

**Comment by macaddr** [comment]
wahoo~
sudo make package  done!!!

and facing a New

it seems like my python is error
By default , the installation version is python3.5.1+
so ，i‘m confused ╮(╯▽╰)╭
I was installed python3.4 ,
maby it's wrong.
> gkh@gkh-office:/home/d/curaProJt/test2/protobuf$ cura
> Traceback (most recent call last):
>   File "/opt/cura/bin/cura_app.py", line 20, in <module>
>     import cura.CuraApplication
>   File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 6, in <module>
>     from UM.Qt.QtApplication import QtApplication
>   File "/opt/cura/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 10, in <module>
>     from PyQt5.QtQml import QQmlApplicationEngine, qmlRegisterType, qmlRegisterSingletonType
> ImportError: /usr/lib/python3/dist-packages/PyQt5/QtNetwork.cpython-34m-x86_64-linux-gnu.so: 
> undefined symbol: _ZTI10QSslSocket

**Comment by Ghostkeeper** [comment]
Python 3.4 should be correct. Your Python is not error.

**Comment by macaddr** [comment]
@Ghostkeeper 
Yes,I'm using GCC. 
I edit the /usr/bin/cura
change "/opt/cura/bin/cura_app.py" to "/opt/cura/bin/cura"

**Comment by Ghostkeeper** [comment]
The picture doesn't work (gives me a 404 error).

I understand that the build succeeded (good job!) but now you're getting a black screen when you start Cura? If so, you're going to need to check whether you have proper support for OpenGL 2 on your computer.

To do that, run `glxinfo | grep "OpenGL version"`. GLXInfo comes, at least on Ubuntu distributions, via the package mesa-utils, so run `apt-get install mesa-utils` first, or whatever your package manager is.
My output is `OpenGL version string: 3.0 Mesa 10.5.9`
Your version string must be at least 2.0.

**Comment by macaddr** [comment]
@Ghostkeeper ,

My output is `OpenGL version string: 2.1 Mesa 11.0.2`

**Comment by Ghostkeeper** [comment]
Huh, should be working okay then. Is there anything in Cura's log?

**Comment by irrenhaus** [comment]
@macaddr What did you do to fix the "Unable to create the C++ source code" error?

Having the same issue on Ubuntu 15.10.

**Comment by ketjow4** [comment]
@macaddr @irrenhaus  How did you make it to pass through that error? I stuck with it and can't build it by any means.

Working on Ubuntu 16.04

**Comment by ahmedelmidany** [comment]
@macaddr  please advise how you solved the below error:
```
Generating the C++ source for the QtGui module...
Error: Unable to create the C++ code.

```
I'm facing the same error while installing PyQt5.

`$python3 configure.py --qmake=/usr/local/Cellar/qt/5.10.1/bin/qmake --sip=/usr/local/Cellar/sip/4.19.8_2/bin/sip`

Installation Environment:
macOS Sierra (version 10.12.6)
PyQt5 GPL 5.7
Qt 5.10
SIP 4.19.8

Two python versions, tried with both versions but same problem.
```
$ python --version
Python 2.7.14

$ python3 --version
Python 3.6.3
```

**Comment by ahmedelmidany** [comment]
Adding --verbose to configure command, I can see the following:

```
Generating the C++ source for the QtCore module...
/usr/local/Cellar/sip/4.19.8_2/bin/sip -w -f -t WS_MACX -t Qt_5_10_1 -B Qt_6_0_0 -P -o -y QtCore.pyi -c /Users/apple/Desktop/Python/PyQt5_gpl-5.7/QtCore -I sip -I /Users/apple/Desktop/Python/PyQt5_gpl-5.7/sip /Users/apple/Desktop/Python/PyQt5_gpl-5.7/sip/QtCore/QtCoremod.sip
sip: Deprecation warning: /Users/apple/Desktop/Python/PyQt5_gpl-5.7/sip/QtCore/QtCoremod.sip:23: %Module version numbers are deprecated and ignored
Error: Unable to create the C++ code.
```

please advise about the solution of this error.

**Comment by ahmedelmidany** [comment]
Managed to solve it, thanks.

**Comment by Ghostkeeper** [comment]
How did you solve the error then? Maybe someone else in the future will run into this as well and could use your help.

**Comment by jerrypy** [comment]
@ahmedelmidany Can you describe how you solve the error?

**Comment by Gerile3** [comment]
Would be great if people who solved the problem just could leave a feedback about it...

**Comment by nelsg** [comment]
Same problem, to solve it I just upgraded all versions :
* sip-4.19.13 
* Qt 5.12.1
* PyQt5_gpl-5.11.3

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.

**Comment by nallath** [comment]
For future reference, downgrading my SIP to 4.19.13 also fixed the issue for me (i had to re-install things after an OS upgrade)
