### ISSUE TITLE
Cannot start Cura

### ISSUE THREAD

**Issue by easonyuexcellent** [Ultimaker/cura-build#47]
~/dev/Cura$ python3 cura_app.py
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/easonyu/dev/Cura/cura/CrashHandler.py", line 8, in <module>
    from UM.i18n import i18nCatalog
ImportError: No module named 'UM'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 18, in <module>
    import Arcus #@UnusedImport
ImportError: No module named 'Arcus'

**Comment by nallath** [comment]
The errors are fairly clear? It cant find Arcus, which is a required library.

**Comment by Ghostkeeper** [comment]
You need to make sure that the path to the Python bindings of libArcus (Arcus.so most likely) is on your PYTHONPATH environment variable.

**Comment by easonyuexcellent** [comment]
Thank U all. I finally succeed in compilling it.
