### ISSUE TITLE
Scipy built before OpenBLAS?

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build#50]
I'm just playing with cura-build and faced this:
```
[ 95%] No update step for 'Scipy'
[ 96%] No patch step for 'Scipy'
[ 97%] No configure step for 'Scipy'
[ 98%] Performing build step for 'Scipy'
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
lapack_opt_info:
openblas_lapack_info:
Replacing _lib_names[0]=='openblas' with 'openblas'
C compiler: cc

creating /tmp/tmpmtm_9op_/tmp
creating /tmp/tmpmtm_9op_/tmp/tmpmtm_9op_
compile options: '-c'
cc: /tmp/tmpmtm_9op_/source.c
/tmp/tmpmtm_9op_/source.c: In function 'main':
/tmp/tmpmtm_9op_/source.c:4:13: warning: implicit declaration of function 'zungqr_' [-Wimplicit-function-declaration]
cc /tmp/tmpmtm_9op_/tmp/tmpmtm_9op_/source.o -L/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib -lopenblas -o /tmp/tmpmtm_9op_/a.out
/tmp/tmpmtm_9op_/tmp/tmpmtm_9op_/source.o: In Funktion `main':
source.c:(.text+0x15): Nicht definierter Verweis auf `zungqr_'
collect2: error: ld returned 1 exit status
/tmp/tmpmtm_9op_/tmp/tmpmtm_9op_/source.o: In Funktion `main':
source.c:(.text+0x15): Nicht definierter Verweis auf `zungqr_'
collect2: error: ld returned 1 exit status
  NOT AVAILABLE

lapack_mkl_info:
mkl_info:
  libraries mkl,vml,guide not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas,tatlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries tatlas,tatlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries satlas,satlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries satlas,satlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries f77blas,cblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries f77blas,cblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/system_info.py:1505: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
lapack_info:
  libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/system_info.py:1516: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
lapack_src_info:
  NOT AVAILABLE

/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/system_info.py:1519: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
  NOT AVAILABLE

Running from scipy source directory.
Traceback (most recent call last):
  File "setup.py", line 253, in <module>
    setup_package()
  File "setup.py", line 250, in setup_package
    setup(**metadata)
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 175, in configuration
    config.add_subpackage('scipy')
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 15, in configuration
    config.add_subpackage('linalg')
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/media/thopiekar/91e97c17-2dbb-47e5-8804-a6f3f4501c8e/Projekte/GIT/Ultimaker/cura-build-copy/build/inst/lib/python3/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/linalg/setup.py", line 20, in configuration
    raise NotFoundError('no lapack/blas resources found')
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
CMakeFiles/Scipy.dir/build.make:114: die Regel für Ziel „Scipy-prefix/src/Scipy-stamp/Scipy-build“ scheiterte
make[2]: *** [Scipy-prefix/src/Scipy-stamp/Scipy-build] Fehler 1
CMakeFiles/Makefile2:476: die Regel für Ziel „CMakeFiles/Scipy.dir/all“ scheiterte
make[1]: *** [CMakeFiles/Scipy.dir/all] Fehler 2
Makefile:105: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 
```

I used ```make package -j8``` to build it even distributed via ```icecc``` and it seems that except of building every dependency one by one it uses every available job to build the next. This is cool, when doing downloads, but when it comes to builds it should really build everything linear and use the available jobs to complete the builds faster.

**Comment by thopiekar** [comment]
Ok, I double checked and OpenBLAS has been built before Scipy, but for a reason it can't find it :disappointed:

**Comment by thopiekar** [comment]
Seems that OpenBLAS is unconfigured on Linux.. Reason for the strange behaviour?
https://github.com/Ultimaker/cura-build/blob/master/CMakeLists.txt#L306

**Comment by thopiekar** [comment]
UPDATE: OpenBLAS has no configuring tool (cmake in development). So this is correct.

**Comment by awhiemstra** [comment]
Yeah the CMake in openblas is unusable due to lacking a proper install target (unfortunatly). As for the multiple jobs, this is up to CMake, which does not pass the -jX on to make when calling it to make a subproject. Which is fairly understandable since you can easily end up with X^2 make jobs. A workaround would be to set the MAKEFLAGS env variable to -jX and then explicitly calling make -j1 for the main build. Alternatively you could look into using ninja (which does automatic paralellisation), though I am not sure how well it copes with something like cura-build.

**Comment by thopiekar** [comment]
It's a strange behaviour, but it works. I guess the most end-users won't
even build cura from source at all.

It looks like adding the FORTRAN check and installing it here, fixed the
problem. Haven't seen that output again..
