### ISSUE TITLE
Run crash after installing cura

### ISSUE THREAD

**Issue by caucycaucy** [Ultimaker/cura-build#64]
Hi All,

  I've built Cura successfully using the building script in my Win10+64bit laptop. And I've also built the installation package. I can run the cura in my laptop. I sent the installation package (Cura-master.0.0-win64) to my friends, and both of them use win7 +64bit. When they run cura, they got the same crash.

Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\curabuild_software\cura-build-master\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py", line 6, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: ((DLL load failed: Can't find the module.) 'C:\Program Files\Cura master.0\sip.pyd') 'C:\Program Files\Cura master.0\PyQt5.QtCore.pyd'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 35, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: ((DLL load failed: Can't find the module.) 'C:\Program Files\Cura master.0\sip.pyd') 'C:\Program Files\Cura master.0\Arcus.pyd'
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "c:\curabuild_software\cura-build-master\build\inst\lib\python3.4\site-packages\cura\CrashHandler.py", line 6, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: ((DLL load failed: Can't find the module.) 'C:\Program Files\Cura master.0\sip.pyd') 'C:\Program Files\Cura master.0\PyQt5.QtCore.pyd'

Original exception was:
Traceback (most recent call last):
  File "cura_app.py", line 35, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: ((DLL load failed: Can't find the module.) 'C:\Program Files\Cura master.0\sip.pyd') 'C:\Program Files\Cura master.0\Arcus.pyd'

  None of them are programers and they don't have python or vs2015 installed in their PC.

 Do you have the similar problem before? 
 Thanks in advance.

Ding

**Comment by Ghostkeeper** [comment]
It looks like your installation package is missing the SIP Python plug-in binary.

If that is not included by cura-build, that'll be a bug.

**Comment by caucycaucy** [comment]
Hi Ghostkeeper,

  Thank you for your reply.  I've searched the installation directory, and there is only one file related with sip, that is "sip.pyd". Is any file missing?
  Thanks in advance.

Ding

**Comment by Ghostkeeper** [comment]
No, that's the one it says is missing... :(

**Comment by JithuPG** [comment]
I'm also facing issuse with running cura Application After successfuly insatlled cura Application while trying to run the Application it quits immediately with out any errors or warnning and also no log dir created .

Build environmnet : win-64

**Comment by Ghostkeeper** [comment]
Maybe the sip.pyd file you built is not compatible with your version of Python? Which compiler was it created with?

**Comment by JithuPG** [comment]
Build with MSV 2017 native x64 ....and i'm  build the dependencies with cura-build-environment ,and it was recommended in build doc . if you trying to build with mingw it freezed the building process at build sip module section i tried that too...

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
