### ISSUE TITLE
Can't run cura after make

### ISSUE THREAD

**Issue by derekhe** [Ultimaker/cura-build#7]
Hi,

I successfully compiled cura using cmake. but when I run the app under build/dist, it says:

Cura Error, 

then "Open Console" will show me:

7/9/15 12:30:16.691 PM Cura[46385]: 2015-07-09 12:30:16.690 Cura[46385:714735] Cura Error
7/9/15 12:30:18.591 PM Cura[46385]: Traceback (most recent call last):
7/9/15 12:30:18.592 PM Cura[46385]:   File "/Users/sche/dev/cura-build/build/dist/Cura.app/Contents/Resources/**boot**.py", line 351, in <module>
7/9/15 12:30:18.592 PM Cura[46385]:     _run()
7/9/15 12:30:18.592 PM Cura[46385]:   File "/Users/sche/dev/cura-build/build/dist/Cura.app/Contents/Resources/__boot__.py", line 336, in _run
7/9/15 12:30:18.592 PM Cura[46385]:     exec(compile(source, path, 'exec'), globals(), globals())
7/9/15 12:30:18.592 PM Cura[46385]:   File "/Users/sche/dev/cura-build/build/dist/Cura.app/Contents/Resources/cura_app.py", line 8, in <module>
7/9/15 12:30:18.592 PM Cura[46385]:     app = cura.CuraApplication.CuraApplication.getInstance()
7/9/15 12:30:18.593 PM Cura[46385]:   File "UM/Application.pyc", line 326, in getInstance
7/9/15 12:30:18.593 PM Cura[46385]:   File "cura/CuraApplication.pyc", line 56, in __init__
7/9/15 12:30:18.593 PM Cura[46385]:   File "UM/Qt/QtApplication.pyc", line 69, in **init**
7/9/15 12:30:18.593 PM Cura[46385]:   File "cura/CuraApplication.pyc", line 110, in _loadPlugins
7/9/15 12:30:18.593 PM Cura[46385]:   File "UM/PluginRegistry.pyc", line 67, in loadPlugin
7/9/15 12:30:18.593 PM Cura[46385]: UM.PluginError.PluginNotFoundError: Could not find plugin CuraEngineBackend
7/9/15 12:30:18.635 PM Console[46402]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable

**Comment by Kriechi** [comment]
I get the very same error - any solutions?
I tried rebuilding multiple times from clean states - without any luck so far...

**Comment by Ghostkeeper** [comment]
Maybe this helps. You need to have the PythonPath set correctly. For me, I just put this in ~/.profile:

    PYTHONPATH=~/Projects/Uranium:/home/ruben/dev/inst/lib/python3/dist-packages
    export PYTHONPATH

You can also call it manually from a terminal. It sets up my PYTHONPATH correctly to be able to run Cura from source. The folders are my Uranium folder and the folder where libArcus was installed to (Arcus.so). You can try pointing them to your own Uranium (it needs the "UM" folder) and Arcus (it needs Arcus.so), which will both be in Cura.app for you, I think. Then I call `python3 cura_app.py` from within Cura's folder to start the program.

The last message, about _consoleX and NSApplication, seems to be a bug in Console itself, and unrelated to Cura. [Source.](https://discussions.apple.com/thread/6814250?start=0&tstart=0)

**Comment by nallath** [comment]
This is how I call it: 
`PYTHONPATH=.:/usr/local/lib/python3/dist-packages/:../Uranium/ python3 cura_app.py`

**Comment by peteruithoven** [comment]
Is there a way to include this into the installation script? (In the make / .sh / .bat files.)

**Comment by nallath** [comment]
Running the installation script actually installs everything correctly for me. This is what I use to run things from source.

**Comment by Kriechi** [comment]
Unfortunately I couldn't get it to work. I have a bunch of folders in my `build` directory, do I need to include them all into the `PYTHONPATH`? This seems a bit strange, why doesn't it auto-detect that?
I'm trying to run the `Cura.app` which is created in `build/dist/Cura.app` - or what is the supposed way to run from source?

**Comment by Ghostkeeper** [comment]
Well usually it wouldn't be necessary but the OSX build works a bit different than what I'm used to.

You wouldn't need to include every folder in your build directory, just the `inst/lib/python3/dist-packages` one.

**Comment by LipuFei** [comment]
Closing this issue due to inactivity.
