### ISSUE TITLE
Win10 build succeeds but exe cannot open up the program

### ISSUE THREAD

**Issue by Ximidar** [Ultimaker/cura-build#88]
When building cura on windows 10 the build succeeds, but now the executable wont start up the program. 

```
Traceback (most recent call last):
  File "cura_app.py", line 10, in <module>
  File "C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\inst\lib\python3.4\site-packages\UM\__init__.py", line 9, in <module>
    from .Application import Application
  File "C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\inst\lib\python3.4\site-packages\UM\Application.py", line 9, in <module>
    from UM.Controller import Controller
  File "C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\inst\lib\python3.4\site-packages\UM\Controller.py", line 4, in <module>
    from UM.Scene.Scene import Scene
  File "C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\inst\lib\python3.4\site-packages\UM\Scene\Scene.py", line 4, in <module>
    from UM.Scene.SceneNode import SceneNode
  File "C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\inst\lib\python3.4\site-packages\UM\Scene\SceneNode.py", line 4, in <module>
    from UM.Math.Matrix import Matrix
  File "C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\inst\lib\python3.4\site-packages\UM\Math\Matrix.py", line 7, in <module>
    import numpy
  File "C:\Anaconda3_64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Anaconda3_64\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3_64\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3_64\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3_64\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 'C:\\Users\\Ximidar\\Documents\\Cura\\test\\cura-build\\build2\\dist\\numpy.core.multiarray.pyd'
```

This is the error that appears in the Cura.log file.
The file 'numpy.core.multiarray.pyd' exists in the same directory as the cura.exe. I'm lost as to what to try next to fix this.

**Comment by thopiekar** [comment]
I wonder if there is a tool like `ldd` on Windows, so you could check, which libraries `numpy.core.multiarray.pyd` needs.
Because for me it sounds like `numpy.core.multiarray.pyd` isn't missing, but one of its dependencies.

**Comment by awhiemstra** [comment]
There is a tool called dependencywalker for Windows that is basically ldd with a UI.

**Comment by Ghostkeeper** [comment]
Another easy check is this:

    SET PYTHONPATH=%PYTHONPATH%;C:\Users\Ximidar\Documents\Cura\test\cura-build\build2\dist
    .\Cura.exe (or whatever you use to run Cura).

**Comment by Ximidar** [comment]
@Ghostkeeper Setting the python path to the dist folder had the same result. As for a dependency issue @awhiemstra the dependency walker did not come up with any new dependencies. It also had trouble actually opening the .pyd file. I'll try a few more times to make sure that's not the issue. Thanks for the help though.

**Comment by Ximidar** [comment]
I ended up making a virtual machine and recompiling it. Everything works now... Not a great solution, but it worked

**Comment by thopiekar** [comment]
That's strange. There seems to be something wrong with your system. However, I'm grad to hear it works at the end. 😉
