### ISSUE TITLE
build ImportError: No module named 'scipy.cluster._hierarchy.cp35-win32'

### ISSUE THREAD

**Issue by twosilly** [Ultimaker/cura-build#95]
build ImportError: No module named 'scipy.cluster._hierarchy.cp35-win32'

Copying NSIS scripts
Running cx_Freeze
Removing previous distribution package

running build
running build_scripts
running build_exe
Traceback (most recent call last):
  File "setup_win32.py", line 125, in <module>
    executables = executables
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\freezer.py", line 621, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\freezer.py", line 340, in _GetModuleFinder
    finder.IncludePackage(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\finder.py", line 659, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\cx_Freeze\finder.py", line 350, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'scipy.cluster._hierarchy.cp35-win32'
CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
mingw32-make[2]: *** [build_exe] Error 1
CMakeFiles\Makefile2:642: recipe for target 'CMakeFiles/build_exe.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

I have installed. python3.5，pip install pyqt5 , install numpy+mkl Wait for all the necessary packages!
The above display has been compiled to complete, but to compile the setup_win32.py times wrong!
 I have installed the SciPy near! Hope here can find the answer, thank you!

**Comment by twosilly-2B** [comment]
@johntron 
@jankeesvw 
@ErikDeBruijn 
@epologee 
@robinmdh 
![qq 20161122084750](https://cloud.githubusercontent.com/assets/21135628/20506641/61420cea-b090-11e6-82dd-f2ee883e2e8f.png)

**Comment by Ghostkeeper** [comment]
If you try this, will it find Scipy?

    python -c "import scipy"

Also, if I recall correctly, Scipy recommends to not get the MKL version of Numpy. You could try with the ordinary one.

**Comment by yingzhang1109** [comment]
same problem here. @twosilly do you solve the problem?

**Comment by LipuFei** [comment]
Closing this issue due to inactivity,.
